<h2 style="text-align: center; background-color: #4d648d; font-family:Arial; color: white; padding: 13px; line-height: 1; border-radius:10px">Initiation Python - Import de fichiers üíª</h2>

# Exercice d'introduction

Faire de la veille sur ces sujets et synth√©tiser vos recherches dans un support de pr√©sentation.

Typologie de donn√©es :
 - Structur√©es vs non structur√©es : d√©finition, exemples, ...
 - Les diff√©rents sources de donn√©es. Trouvez les packages en Python qui permet notamment de pouvoir importer/se connecter aux donn√©es.

In [ ]:
# Importer les biblioth√®ques n√©cessaires
from google.colab import drive
import pandas as pd

# Monter Google Drive
drive.mount('/content/drive')

# Chemin du fichier dans Google Drive (exemple)
csv_file_path = '/content/drive/MyDrive/nom_du_fichier.csv'  # Remplacez 'nom_du_fichier.csv' par le nom de votre fichier
txt_file_path = '/content/drive/MyDrive/nom_du_fichier.txt'  # Remplacez 'nom_du_fichier.txt' par le nom de votre fichier

# Lire un fichier CSV
df_csv = pd.read_csv(csv_file_path)
print("Contenu du fichier CSV :")
print(df_csv.head())

# Lire un fichier TXT
# Sp√©cifiez le d√©limiteur si n√©cessaire, ici on utilise un espace comme exemple
df_txt = pd.read_csv(txt_file_path, delimiter=' ')
print("\nContenu du fichier TXT :")
print(df_txt.head())

<h2 style="text-align: center; background-color: #87c7ec; font-family:Arial; color: white; padding: 13px; line-height: 1; border-radius:10px">MISE EN PRATIQUE</h2>

### Import fichier


Import des fichiers et stockage de mani√®re propre dans des dataframes. Vous risquez d'avoir besoin de fonctions sp√©cifiques, uniquement disponible dans certains packages. N'h√©sitez pas √† regarder sur Google pour vous aider !  
Les 3 fichiers √† importer :
> prima.txt  
> mar2012.csv

In [4]:
# Importer les biblioth√®ques n√©cessaires
from google.colab import drive
import pandas as pd

# Monter Google Drive
drive.mount('/content/drive')

# Chemin du fichier dans Google Drive (exemple)
csv_file_path = '/content/drive/MyDrive/Oreegami - Codage/Jour 1/Donn√©es/mar2012.csv'  # Remplacez 'nom_du_fichier.csv' par le nom de votre fichier
txt_file_path = '/content/drive/MyDrive/Oreegami - Codage/Jour 1/Donn√©es/prima.txt'  # Remplacez 'nom_du_fichier.txt' par le nom de votre fichier

# Lire un fichier CSV
df_csv = pd.read_csv(csv_file_path, encoding = 'latin-1', skiprows=3)
print("Contenu du fichier CSV :")
print(df_csv.head())

# Lire un fichier TXT
# Sp√©cifiez le d√©limiteur si n√©cessaire, ici on utilise un espace comme exemple
df_txt = pd.read_csv(txt_file_path, delimiter='\t')
print("\nContenu du fichier TXT :")
print(df_txt.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Contenu du fichier CSV :
   ANAISH DEPNAISH  INDNATH  ETAMATH  ANAISF DEPNAISF  INDNATF  ETAMATF  AMAR  \
0    1982       75        1        1    1984       99        2        1  2012
1    1956       69        2        4    1969       99        2        4  2012
2    1982       99        2        1    1992       99        1        1  2012
3    1985       99        2        1    1987       84        1        1  2012
4    1968       99        2        1    1963       99        2        1  2012

   MMAR  JSEMAINE DEPMAR DEPDOM  TUDOM TUCOM NBENFCOM
0     1         1     29     99      9   NaN        N
1     1         3     75     99      9   NaN        N
2     1         5     34     99      9   NaN        N
3     1         4     13     99      9   NaN        N
4     1         6     26     99      9   NaN        N

Contenu du fichier TXT :
   pregnant  glucose  diastolic  triceps  insulin   bmi  diabetes  age  test
0         6      148         72       35        0  33.6     0.627   50     1
1         1       85         66       29        0  26.6     0.351   31     0
2         8      183         64        0        0  23.3     0.672   32     1
3         1       89         66       23       94  28.1     0.167   21     0
4         0      137         40       35      168  43.1     2.288   33     1

<ipython-input-4-2ccf4b89cee6>:13: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_csv = pd.read_csv(csv_file_path, encoding = 'latin-1', skiprows=3)

#### 2. Afficher les donn√©es

In [6]:
df_csv

,ANAISH,DEPNAISH,INDNATH,ETAMATH,ANAISF,DEPNAISF,INDNATF,ETAMATF,AMAR,MMAR,JSEMAINE,DEPMAR,DEPDOM,TUDOM,TUCOM,NBENFCOM
0,1982,75,1,1,1984,99,2,1,2012,1,1,29,99,9,NaN,N
1,1956,69,2,4,1969,99,2,4,2012,1,3,75,99,9,NaN,N
2,1982,99,2,1,1992,99,1,1,2012,1,5,34,99,9,NaN,N
3,1985,99,2,1,1987,84,1,1,2012,1,4,13,99,9,NaN,N
4,1968,99,2,1,1963,99,2,1,2012,1,6,26,99,9,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246118,1948,99,1,4,1955,27,1,1,2012,12,6,978,978,9,P,N
246119,1961,99,1,4,1976,99,2,1,2012,12,6,978,978,9,P,O
246120,1963,60,1,4,1970,971,1,4,2012,12,5,978,978,9,P,N
246121,1973,99,2,1,1985,971,1,1,2012,12,5,978,978,9,P,N
246122,1980,99,2,1,1982,90,1,1,2012,12,5,978,978,9,P,N

Utiliser les fonctions head() et tail() pour afficher les 5 premi√®res et 5 derni√®res lignes du dataset

‚ùì Quelle est la taille du dataset ? Utiliser la fonction shape et interpr√©ter le r√©sultat

In [7]:
df_csv.shape

(246123, 16)

246123 lignes et 16 colonnes

Afficher toutes les colonnes du dataset avec un 'columns'

In [8]:
df_csv.columns

Index(['ANAISH', 'DEPNAISH', 'INDNATH', 'ETAMATH', 'ANAISF', 'DEPNAISF',
       'INDNATF', 'ETAMATF', 'AMAR', 'MMAR', 'JSEMAINE', 'DEPMAR', 'DEPDOM',
       'TUDOM', 'TUCOM', 'NBENFCOM'],
      dtype='object')

S√©lectionner uniquement une colonne   
Vous pouvez vous inspirer de cette documentation : [Aide](https://apprendrepython.com/pandas-selectionner-des-lignes-colonnes-dans-un-dataframe-en-indexant/)

In [9]:
df_csv['DEPDOM']

0          99
1          99
2          99
3          99
4          99
         ...
246118    978
246119    978
246120    978
246121    978
246122    978
Name: DEPDOM, Length: 246123, dtype: object

Regarder le nombre de personnes n√©es selon les mois, avec MMAR (utiliser la fonction [value_counts](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html) )

In [10]:
df_csv['MMAR'].value_counts()

MMAR
6     42880
9     36071
7     32524
8     31543
5     26350
4     16780
10    14149
12    13446
3      9896
11     9303
2      7151
1      6030
Name: count, dtype: int64

‚ùì Quelle est la moyenne de MMAR ?

In [11]:
df_csv['MMAR'].mean()

6.9721074422138525

‚ùì Quelle est la valeur maximale de MMAR ?

In [ ]:
df_csv['MMAR'].max()

S√©lectionner uniquement les donn√©es pour lesquelles le mois >= 6 et stocker le r√©sultat dans une nouvelle variable

In [12]:
df_csv[df_csv['MMAR']>6]

,ANAISH,DEPNAISH,INDNATH,ETAMATH,ANAISF,DEPNAISF,INDNATF,ETAMATF,AMAR,MMAR,JSEMAINE,DEPMAR,DEPDOM,TUDOM,TUCOM,NBENFCOM
754,1984,99,2,1,1985,974,1,1,2012,7,3,974,99,9,NaN,N
757,1981,75,2,1,1980,75,1,1,2012,7,2,75,99,9,NaN,N
759,1976,99,2,1,1976,75,1,1,2012,7,4,91,99,9,NaN,N
760,1981,33,1,1,1984,59,1,1,2012,7,5,44,99,9,NaN,N
762,1961,47,1,4,1968,99,2,4,2012,7,5,64,99,9,NaN,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246118,1948,99,1,4,1955,27,1,1,2012,12,6,978,978,9,P,N
246119,1961,99,1,4,1976,99,2,1,2012,12,6,978,978,9,P,O
246120,1963,60,1,4,1970,971,1,4,2012,12,5,978,978,9,P,N
246121,1973,99,2,1,1985,971,1,1,2012,12,5,978,978,9,P,N
246122,1980,99,2,1,1982,90,1,1,2012,12,5,978,978,9,P,N

#### 3. Export des donn√©es

**Pour √©crire des donn√©es dans un fichier texte (`.txt`) :**

data = ["Ligne 1", "Ligne 2", "Ligne 3"]

with open("data.txt", "w") as file:  
        file.write("\n".join(data))
    

**Pour √©crire des donn√©es dans un fichier csv (`.csv`) :**

import pandas as pd

df = pd.DataFrame(data[1:], columns=data[0])  
df.to_csv("data.csv", index=False)


**Pour √©crire des donn√©es dans un fichier Excel (`.xlsx`) :**

import pandas as pd  
df = pd.DataFrame(data)  
df.to_excel("data.xlsx", index=False)